## PyTorch Foundation

In [ ]:
print("Hello I am excited to work in Python")

Hello I am excited to work in Python


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


##00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


## INtro to tensor

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item() # tensor back as python int

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [2,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 5, 6]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

#RANDOM TENSOR

In [ ]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.6445, 0.4372, 0.6380, 0.1344],
         [0.3059, 0.1694, 0.3777, 0.6125],
         [0.9109, 0.4155, 0.0692, 0.2180]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## ZEROS AND ONE

In [ ]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#tensor of onee
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
## creating a range of tensors and tensors like
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = torch.arange(start=0,end=1000, step=77)
x

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#tensor datatype

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None,
                               device=None,
                               requires_grad=False)
float_32_tensor


tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)

In [ ]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
mul = float_16_tensor * float_32_tensor
mul.dtype

torch.float32

1. Tensor datatype - tensor.dtype
2. Tensor shape - tensor.shape
3. Tensor device - tensor.device

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2373, 0.8586, 0.2710, 0.5337],
        [0.8274, 0.5944, 0.8629, 0.2413],
        [0.3116, 0.1292, 0.8234, 0.0229]])

In [ ]:
print(some_tensor)
print(f" Datatype  :{some_tensor.dtype}")
print(f" Shape  :{some_tensor.shape}")
print(f" Device: {some_tensor.device}")


tensor([[0.2373, 0.8586, 0.2710, 0.5337],
        [0.8274, 0.5944, 0.8629, 0.2413],
        [0.3116, 0.1292, 0.8234, 0.0229]])
 Datatype  :torch.float32
 Shape  :torch.Size([3, 4])
 Device: cpu


In [ ]:
some_tensor2 = torch.rand(2,3)
some_tensor2 =some_tensor2.type(torch.half)
some_tensor2

tensor([[0.4973, 0.4988, 0.8716],
        [0.5381, 0.9873, 0.0189]], dtype=torch.float16)

In [ ]:
print(some_tensor2)
print(f"datatype : {some_tensor2.dtype}")
print(f"Size : {some_tensor2.shape}")
print(f"Device : {some_tensor2.device}")

tensor([[0.4973, 0.4988, 0.8716],
        [0.5381, 0.9873, 0.0189]], dtype=torch.float16)
datatype : torch.float16
Size : torch.Size([2, 3])
Device : cpu


In [ ]:
tensor_demo = torch.tensor([1,2,4])

In [ ]:
torch.mul(tensor_demo,10)

tensor([10, 20, 40])

In [ ]:
torch.add(tensor_demo, 2)

tensor([3, 4, 6])

# MATRIX MULTIPLICATION

In [ ]:
#ELEMENT WISE MULTIPLY
tensor = torch.tensor([1,2,3])#,
                        #[3,4,5],
                        #[2,5,6]]])
print(tensor)
print(f"Equals:  {tensor * tensor}")

tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [ ]:
torch.matmul(tensor_A, tensor_B)
#above code wont work because of size issue. fix by below code

RuntimeError: ignored

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
#matrix mul work when tensor_B is transposed
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
#Tensor Aggregation - min, max, mean, sum etc
x= torch.arange(0, 100, 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x) ,x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
x.dtype
x.mean(), torch.mean(x)
#the error saying for mean we need floating point or complex dtype.

RuntimeError: ignored

In [ ]:
#converting to float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.argmin(x)

tensor(0)

In [ ]:
torch.argmax(x)

tensor(9)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

##reshaping, staking, squeezing and unsqueezing tensors
# reshape - reshape to define shape
#view - reurn view of the input tensor
#stacking - combine multiple tensors - vstack, hstack
#squeeze - remove 1 demension to a target tensor
#unsqueeze - add 1 dimention
#permute - return a view - dimensions permuted( swapped) in a certain way


In [ ]:
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
y_reshaped = x.reshape(1, 9)
y_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#change the view
z = x.view(1, 9)
z

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
z[0] = 5
z,x

(tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [ ]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [ ]:
 x_reshaped.shape

torch.Size([9, 1])

In [ ]:
 x_squeezed = x_reshaped.squeeze()#.shape

In [ ]:
#unsqueeze() - torch - adds single dimention

print(f"Previous target:{x_squeezed}")
print(f"Previous target:{x_squeezed.shape}")

Previous target:tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])
Previous target:torch.Size([9])


In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\n new tensor : {x_unsqueezed}")


 new tensor : tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]])


In [ ]:
#permute - change the position
x_original = torch.rand(size=(224,224,3))

# permute the original tensor
x_permuted = x_original.permute(2,0,1)
print(f" Previous shape: {x_original.shape}")
print(f" Previous shape: {x_permuted.shape}")

#x_permuted

 Previous shape: torch.Size([224, 224, 3])
 Previous shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0]
x_original[0,0,0] = .876
x_original[0,0,0], x_permuted[0,0,0]

(tensor(0.8760), tensor(0.8760))

In [ ]:
#indexing(selecting data from the tensors)

import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0,2,2], x[0][2][2]

(tensor(9), tensor(9))

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[0,:,2]

tensor([3, 6, 9])

In [ ]:
#PyTorch tensor & NumPy
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning convertion from float64 to float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype # default dtype of numpy

dtype('float64')

In [ ]:
#what is the default datatype of pyTorch
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Go back to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
## reproducability (trying to take random out of random)
torch.rand(3,3)

tensor([[0.6612, 0.8016, 0.7487],
        [0.1151, 0.5008, 0.2037],
        [0.4595, 0.5306, 0.5857]])

In [ ]:
#to reduce the randomeness and pytorch comes the concept of
##**RANDOM SEED**
##WHAT IS DOES? flavor the randomness


In [ ]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7470, 0.6607, 0.9306, 0.2112],
        [0.0157, 0.3256, 0.8752, 0.5498],
        [0.3297, 0.1669, 0.7790, 0.7357]])
tensor([[0.4844, 0.6785, 0.5447, 0.2911],
        [0.8995, 0.1302, 0.8707, 0.8929],
        [0.0877, 0.6421, 0.3855, 0.0891]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
##RUNNING GPU
## CUDA + NVIDIA + PYTORCH

#change to GPU
#CHECK NVIDIA - GPU

!nvidia-smi

Thu Oct 26 22:23:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
#CHECK FOR GPU ACCESS WITH PYTORCH
import torch
torch.cuda.is_available()

True

In [ ]:
#SET UP DEVICE AGNOSTIC CODE

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#COUNT THE NUMBER OF GPU
torch.cuda.device_count()

1

In [ ]:
#Put the tensors and model on GPU
tensor = torch.tensor([1,2,3], device='cpu')
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#if tensor is on GPU, cant transforn it to numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [7]:
#Exercise
import torch
x = torch.rand(7,7)
x, x.shape

(tensor([[0.1021, 0.5808, 0.9256, 0.3897, 0.5381, 0.3720, 0.7379],
         [0.9513, 0.1712, 0.3973, 0.3028, 0.6212, 0.7573, 0.9126],
         [0.6351, 0.2177, 0.1249, 0.1087, 0.1404, 0.0609, 0.9393],
         [0.9898, 0.1993, 0.1036, 0.9179, 0.6113, 0.5013, 0.4122],
         [0.8928, 0.2857, 0.3795, 0.7015, 0.8075, 0.5787, 0.2198],
         [0.8132, 0.4824, 0.0016, 0.8638, 0.7047, 0.1275, 0.3820],
         [0.0020, 0.8962, 0.0988, 0.3145, 0.2911, 0.8009, 0.2400]]),
 torch.Size([7, 7]))

In [8]:
y = torch.rand(1,7)
y, y.shape

(tensor([[0.0676, 0.3700, 0.8311, 0.6876, 0.9298, 0.6989, 0.9753]]),
 torch.Size([1, 7]))

In [13]:
z = torch.matmul(x,y.T)
z, z.shape

(tensor([[2.7390],
         [2.6628],
         [1.3911],
         [2.1786],
         [2.3334],
         [1.9456],
         [1.6946]]),
 torch.Size([7, 1]))

In [16]:
RANDOM_SEED=0
torch.manual_seed(RANDOM_SEED)
x = torch.rand(7,7)
print(x)
torch.manual_seed(RANDOM_SEED)
y = torch.rand(1,7)
z = torch.matmul(x,y.T)
z

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [17]:
torch.cuda.manual_seed(1234)

In [20]:
torch.manual_seed(1234)

device="cuda" if torch.cuda.is_available() else "cpu"
print(f" Device: {device}")

tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
print(f" Tensor_A: {tensor_A}")
print(f"Tensor_B: {tensor_B}")

 Device: cuda
 Tensor_A: tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
Tensor_B: tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [23]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [24]:
max = torch.max(tensor_C)
min = torch.min(tensor_C)
print(f"Max : {max}")
print(f"Min : {min}")

Max : 0.5617256760597229
Min : 0.3647301495075226


In [28]:
arg_max= torch.argmax(tensor_C)

arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [31]:
torch.manual_seed(7)

tensor_D = torch.rand(size=(1,1,1,10))

tensor_E = tensor_D.squeeze()

print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
